tanhua:
  sms:
    signName: 测试短信
    templateCode: xx
    accessKey: xxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxx
  oss:
    accessKey: xx
    secret: x
    endpoint: xx
    bucketName: xx
    url: xx

  aip:
    appId: x
    apiKey: xx
    secretKey: x

server:
  port: 18080
spring:
  application:
    name: tanhua-app-service
  redis:
    port: 6379
    host: 192.168.136.160
  cloud:
    nacos:
     discovery:
       server-addr: 192.168.136.160:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
