server:
  port: 18082
spring:
  application:
    name: tanhua-dubbo-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tanhua?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2788
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 192.168.136.160:8848

dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.tanhua.dubbo.api #dubbo中的包扫描


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_  #表前缀
      id-type: auto  #id策略为自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl