tanhua:
  sms:
    signName: 测试短信
    templateCode: SMS_154950909
    accessKey: x
    secret: x
  oss:
    accessKey: x
    secret: x
    endpoint: x
    bucketName: x
    url: x

  aip:
    appId: x
    apiKey: x
    secretKey: x

server:
  port: 18080
spring:
  application:
    name: tanhua-app-service
  redis:
    port: 6379
    host: 192.168.136.160
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
