tanhua:
  sms:
    signName: 测试短信
    templateCode: SMS_123456677
    accessKey: xxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxx
  oss:
    accessKey: LTAI5tJUV3eYXNLNe6DSq2q1
    secret: 6vtlVoziC8X23TjM1GwrOUrhidFQ1s
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: leahana-tanhua
    url: https://leahana-tanhua.oss-cn-hangzhou.aliyuncs.com/

server:
  port: 18080
spring:
  application:
    name: tanhua-app-service
  redis:
    port: 6379
    host: 192.168.136.160
  cloud:
    nacos:
     discovery:
       server-addr: 192.168.136.160:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
